// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-rTsd1zJSEfBlMpC2kBBjbox_rXoBgGU',
    appId: '1:686083564926:web:d16f7c3d406c3c56573f2f',
    messagingSenderId: '686083564926',
    projectId: 'hanacemi-a175c',
    authDomain: 'hanacemi-a175c.firebaseapp.com',
    databaseURL: 'https://hanacemi-a175c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hanacemi-a175c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk0_IpZ7O3jHRfJTeZgGM2waGpimoVEmU',
    appId: '1:686083564926:android:1ac95af8c30c19ec573f2f',
    messagingSenderId: '686083564926',
    projectId: 'hanacemi-a175c',
    databaseURL: 'https://hanacemi-a175c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hanacemi-a175c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO9f74No9vPWIEGns_EhSyrZRHQ8YXBQk',
    appId: '1:686083564926:ios:76e2b4d2a2ea0864573f2f',
    messagingSenderId: '686083564926',
    projectId: 'hanacemi-a175c',
    databaseURL: 'https://hanacemi-a175c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hanacemi-a175c.firebasestorage.app',
    iosBundleId: 'com.hey-show.sozoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO9f74No9vPWIEGns_EhSyrZRHQ8YXBQk',
    appId: '1:686083564926:ios:63da69211358968b573f2f',
    messagingSenderId: '686083564926',
    projectId: 'hanacemi-a175c',
    databaseURL: 'https://hanacemi-a175c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hanacemi-a175c.firebasestorage.app',
    iosBundleId: 'q',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-rTsd1zJSEfBlMpC2kBBjbox_rXoBgGU',
    appId: '1:686083564926:web:5ece685843f9d104573f2f',
    messagingSenderId: '686083564926',
    projectId: 'hanacemi-a175c',
    authDomain: 'hanacemi-a175c.firebaseapp.com',
    databaseURL: 'https://hanacemi-a175c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hanacemi-a175c.firebasestorage.app',
  );

}